# Generated by Django 5.1.6 on 2025-03-06 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_alter_users_photo_users_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_photo',
            name='fk_users_aut_user',
        ),
        migrations.AddField(
            model_name='users_photo',
            name='fk_users_aut_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
