# Generated by Django 5.1.6 on 2025-03-06 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_remove_users_photo_fk_users_aut_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_photo',
            name='fk_users_aut_user',
        ),
        migrations.AddField(
            model_name='users_photo',
            name='fk_users_aut_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
