# Generated by Django 5.1.6 on 2025-03-06 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes_name', models.CharField(blank=True, max_length=240, null=True, verbose_name='Nombre del anime')),
                ('animes_sypnosis', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Sinopsis del anime')),
                ('animes_status', models.BooleanField(default=False, verbose_name='Estado del anime')),
                ('animes_type', models.CharField(blank=True, max_length=240, null=True, verbose_name='Tipo de anime')),
                ('animes_chapters', models.IntegerField(blank=True, null=True, verbose_name='Capitulos del anime')),
                ('animes_release_year', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento del anime')),
                ('animes_poster', models.ImageField(blank=True, max_length=200, null=True, upload_to='animes_poster/', verbose_name='Imagen del anime')),
            ],
        ),
        migrations.CreateModel(
            name='animes_genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animes_genders_name', models.CharField(blank=True, max_length=240, null=True, verbose_name='Genero del anime')),
            ],
        ),
        migrations.CreateModel(
            name='gender_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_gender_list_anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.animes')),
                ('fk_gender_list_animes_genders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.animes_genders')),
            ],
        ),
    ]
