# Generated by Django 5.1.6 on 2025-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animes',
            old_name='animes_poster',
            new_name='animes_poster_url',
        ),
        migrations.AddField(
            model_name='animes',
            name='animes_genders',
            field=models.ManyToManyField(blank=True, related_name='animes', to='administrator.animes_genders'),
        ),
        migrations.DeleteModel(
            name='gender_list',
        ),
    ]
