# Generated by Django 5.1.6 on 2025-03-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_animes_poster_animes_animes_poster_url_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animes',
            table='anime',
        ),
        migrations.AlterModelTable(
            name='animes_genders',
            table='anime_genders_table',
        ),
    ]
