# Generated by Django 5.1.6 on 2025-03-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_animes_table_alter_animes_genders_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animes_genders',
            table='anime_genders',
        ),
    ]
