# Generated by Django 5.1.6 on 2025-03-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_animes_genders_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='animes_poster_url',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='posters/', verbose_name='Imagen del anime'),
        ),
    ]
